name: CI Pipeline

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt
        pip install pytest  # Ensure pytest is installed for running tests

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 src || true  # prevent breaking on lint issues

    - name: Run App
      run: |
        echo "Running app.py to show greeting..."
        python src/app.py

    - name: Run Unit Tests if present
      run: |
          pip install pytest
          pytest src/  # Run all tests in the 'src' directory
        else
          echo "No tests/ directory found. Skipping tests."
        fi

    - name: Snyk Dependency Scan
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --file=requirements.txt

    - name: Install Snyk CLI for Code Scan
      uses: snyk/actions/setup@master

    - name: Run Snyk Code Scan
      run: snyk code test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
